# Generated by Django 4.2.7 on 2025-10-17 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('project_report', 'Project Report'), ('job_description', 'Job Description'), ('case_study_brief', 'Case Study Brief'), ('cv_rubric', 'CV Scoring Rubric'), ('project_rubric', 'Project Scoring Rubric')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_by', models.UUIDField(blank=True, help_text='User ID who uploaded the document', null=True)),
            ],
            options={
                'db_table': 'shared_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shared_system_config',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('api', 'API Service'), ('worker', 'Worker Service'), ('database', 'Database'), ('redis', 'Redis'), ('llm', 'LLM Service'), ('vector_db', 'Vector Database')], max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('degraded', 'Degraded')], max_length=20)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'shared_health_check',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_name', 'created_at'], name='shared_heal_service_2a051f_idx'), models.Index(fields=['status', 'created_at'], name='shared_heal_status_fdb1b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('user_action', 'User Action'), ('system_event', 'System Event'), ('api_call', 'API Call'), ('error', 'Error'), ('evaluation', 'Evaluation')], max_length=50)),
                ('event_name', models.CharField(max_length=255)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shared_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='shared_audi_event_t_282aeb_idx'), models.Index(fields=['user_id', 'created_at'], name='shared_audi_user_id_759bc5_idx'), models.Index(fields=['resource_id', 'resource_type'], name='shared_audi_resourc_52966c_idx')],
            },
        ),
    ]
